import json
from setup_and_ingestion import *

def look_up() -> dict:
    ''' Takes two inputs from the user and returns information about a specific item from the Hyrule Compendium. First input is the category, second input is the item to look up. Valid categories are creature, equipment, material, monster, treasure. Valid items are generated by the valid items function in the setup file. '''

    user_category = input('Please choose one of the following categories: creature, equipment, material, monster, treasure:\n')
    if user_category not in ['creature', 'equipment', 'material', 'monster', 'treasure']:
        print('Invalid category. Please re-run the programme to try again.') 
    else: 
        user_item = input(f'Great! Now choose a valid {user_category} to look up:\n')
        if user_category in ['creature', 'material', 'monster']:
            user_category = f'{user_category}s'
        result = create_valid_items_lists()[user_category]
        if user_item not in result:
            print('Invalid choice. Please re-run the programme to try again.')
        else:
            # reads the appropriate file from the compendium_data dir based on user input
            with open(f'compendium_data/{user_category}.json', 'r', encoding='utf-8') as f:
                data = json.loads(f.read())
                for item in data:
                    if item['name'] == user_item:
                        print(item)
                        return item
                    
look_up()

